/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Code;

import processing.core.PVector;

public class PlanetCustom extends javax.swing.JDialog {

    Planet p;
    
    public PlanetCustom(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    public void set(Planet planet){
        p = planet;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        radiusBox = new javax.swing.JTextField();
        massBox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        colorBox = new javax.swing.JTextField();
        yVelocityBox = new javax.swing.JTextField();
        xVelocityBox = new javax.swing.JTextField();
        staticCheck = new javax.swing.JCheckBox();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radiusBox.setBackground(new java.awt.Color(204, 204, 204));
        radiusBox.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        panel.add(radiusBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 170, 40));

        massBox.setBackground(new java.awt.Color(204, 204, 204));
        massBox.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        panel.add(massBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 170, 40));

        jButton1.setBackground(new java.awt.Color(0, 204, 102));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("✔");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 110, 40));

        colorBox.setBackground(new java.awt.Color(204, 204, 204));
        colorBox.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        panel.add(colorBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 352, 170, 40));

        yVelocityBox.setBackground(new java.awt.Color(204, 204, 204));
        panel.add(yVelocityBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 60, -1));

        xVelocityBox.setBackground(new java.awt.Color(204, 204, 204));
        panel.add(xVelocityBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 60, -1));

        staticCheck.setBackground(new java.awt.Color(251, 206, 177));
        staticCheck.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        staticCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staticCheckActionPerformed(evt);
            }
        });
        panel.add(staticCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 40, 40));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/universe.jpg"))); // NOI18N
        panel.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        String massString = massBox.getText();
        String radiusString = radiusBox.getText();
        String colourString = colorBox.getText();
        String[] colours = colourString.split(",");
        
        float xVelocity;
        float yVelocity;
        
        if(xVelocityBox.getText().equals("")){
            xVelocity = 0;
        }
        else{
            xVelocity = Float.valueOf(xVelocityBox.getText());
        }
        if(yVelocityBox.getText().equals("")){
            yVelocity = 0;
        }
        else{
            yVelocity = Float.valueOf(yVelocityBox.getText());
        }
        
        if(staticCheck.isSelected()){
            p.setStatic(true);
        }else{
            p.setStatic(false);
        }
         
        p.setMass(Long.valueOf(massString).longValue());   
        p.setRadius(Long.valueOf(radiusString).longValue());
        p.setColor(Integer.valueOf(colours[0]), Integer.valueOf(colours[1]), Integer.valueOf(colours[2]));
        p.setVelocity(new PVector(xVelocity,yVelocity));
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void staticCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staticCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staticCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanetCustom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanetCustom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanetCustom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanetCustom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlanetCustom dialog = new PlanetCustom(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JTextField colorBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField massBox;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField radiusBox;
    private javax.swing.JCheckBox staticCheck;
    private javax.swing.JTextField xVelocityBox;
    private javax.swing.JTextField yVelocityBox;
    // End of variables declaration//GEN-END:variables
}
